# Generated by Django 6.1.1 on 2026-10-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Alerta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'RegistroAuditoria',
                'managed': True,
            },
        ),
    ]
