# Generated by Django 6.1.1 on 2026-10-06 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='documento',
            field=models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='documento',
            field=models.ForeignKey(blank=True, db_column='id_documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to='documentos.documento'),
        ),
    ]
