# Generated by Django 6.1.1 on 2026-10-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('sistema_relacionado', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentoEtiqueta',
            fields=[
                ('id_documento_etiqueta', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DocumentoEtiqueta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id_etiqueta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Etiqueta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormatoArchivo',
            fields=[
                ('id_formato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formato de Archivo',
                'verbose_name_plural': 'Formatos de Archivo',
                'db_table': 'FormatoArchivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PermisoDocumento',
            fields=[
                ('id_permiso_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_acceso', models.CharField(blank=True, max_length=50, null=True)),
                ('permitido', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'PermisoDocumento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SugerenciaInteligente',
            fields=[
                ('id_sugerencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sugerencia', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_sugerido', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_final', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SugerenciaInteligente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'TipoDocumento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id_version', models.AutoField(primary_key=True, serialize=False)),
                ('numero_version', models.IntegerField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('comentario_cambio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VersionDocumento',
                'managed': True,
            },
        ),
    ]
