# Generated by Django 6.1.1 on 2026-10-06 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='area',
            field=models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='usuarios.area'),
        ),
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.categoria'),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario_responsable',
            field=models.ForeignKey(blank=True, db_column='id_usuario_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoetiqueta',
            name='documento',
            field=models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='documentoetiqueta',
            name='etiqueta',
            field=models.ForeignKey(db_column='id_etiqueta', on_delete=django.db.models.deletion.CASCADE, to='documentos.etiqueta'),
        ),
        migrations.AddField(
            model_name='permisodocumento',
            name='documento',
            field=models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='permisodocumento',
            name='permiso',
            field=models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, to='usuarios.permiso'),
        ),
        migrations.AddField(
            model_name='permisodocumento',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sugerenciainteligente',
            name='documento',
            field=models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='sugerenciainteligente',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.tipodocumento'),
        ),
        migrations.AddField(
            model_name='versiondocumento',
            name='documento',
            field=models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='versiondocumento',
            name='formato',
            field=models.ForeignKey(db_column='id_formato', on_delete=django.db.models.deletion.PROTECT, to='documentos.formatoarchivo'),
        ),
        migrations.AddField(
            model_name='versiondocumento',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documentoetiqueta',
            unique_together={('documento', 'etiqueta')},
        ),
    ]
